<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="report" type="reportRoot"/>

    <xs:complexType name="reportRoot">
        <xs:sequence>
            <xs:element name="metaInfos" type="metaInfos" minOccurs="0"/>
            <xs:element name="features" type="features" minOccurs="0"/>
            <xs:element name="testSuites" type="testSuites" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="metaInfos">
        <xs:sequence>
            <xs:element name="metaInfo" type="metaInfo" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="features">
        <xs:sequence>
            <xs:element name="feature" type="feature" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="testSuites">
        <xs:sequence>
            <xs:element name="testSuite" type="testSuite" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="feature">
        <xs:sequence>
            <xs:element name="mappedTestCases" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="id" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="testSuite">
        <xs:sequence>
            <xs:element name="comment" type="xs:string" minOccurs="0"/>
            <xs:element name="metaInfos" type="metaInfos" minOccurs="0"/>
            <xs:element name="testCases" type="testCases" minOccurs="0"/>
            <!-- svg diagram encoded with gzip + base64 -->
            <xs:element name="testTraceDiagram" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="testCases">
        <xs:sequence>
            <xs:element name="testCase" type="testCase" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="testCase">
        <xs:sequence>
            <xs:element name="metaInfos" type="metaInfos" minOccurs="0"/>
            <xs:element name="comment" type="xs:string" minOccurs="0"/>
            <xs:element name="frameworkMessage" minOccurs="0">
                <!-- output from unit framework -->
                <xs:complexType mixed="true">
                    <xs:attribute name="message" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="stdout" type="xs:string" minOccurs="0" />
            <xs:element name="stderr" type="xs:string" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="testSuite" type="xs:string" use="required"/>
        <xs:attribute name="result" type="testResult" use="required"/>
        <xs:attribute name="executionTime" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="testResult">
        <xs:restriction base="xs:string">
            <xs:enumeration value="notExecuted"/>
            <xs:enumeration value="passed"/>
            <xs:enumeration value="skipped"/>
            <xs:enumeration value="failed"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="metaInfo">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="key" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>
