name: test 
run-name: ${{ github.actor }} is learning GitHub Actions
on: push

defaults:
  run:
    shell: cmd

jobs:
  #  download-artifact:
  #
  flash:
    runs-on: [self-hosted, windows, x64, miniHIL_runner]
    #needs: download-artifact
    steps:
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build
      - name: Flash with Gradle
        run: ./gradlew flash
