name: test 
run-name: ${{ github.actor }} is learning GitHub Actions
on: push

### use cmd as default shell ###
defaults:
  run:
    shell: cmd
  runs-on: [miniHIL_runner]

### begin jobs ###
jobs:
  #  download-artifact:
  #
  ### first job "flash" ###
  flash:
    #needs: download-artifact
    steps:
      - name: Build with Gradle
        run: |
          cd C:\miniHIL\TS7x_MotorController_miniHIL\MiniHilPilot
          .\gradlew.bat build
      - name: Flash with Gradle
        run: |
          cd C:\miniHIL\TS7x_MotorController_miniHIL\MiniHilPilot
          .\gradlew.bat flash


