name: MiniHIl Test 
on: push
#  branches:
#    - tbd

### use cmd as default shell ###
defaults:
  run:
    shell: cmd

### begin jobs ###
jobs:
  ### first job "prepare-miniHIL" ###
  prepare-miniHIL:
    runs-on: [miniHIL_runner]
    steps:
      - name: Build, Flash and Reset with Gradle
        run: .\gradlew.bat build flash reset
        working-directory: c:\minihil\ts7x_motorcontroller_minihil\minihilpilot

  prepare-motorController:
    runs-on: [miniHIL_runner]
    needs: prepare-miniHIL
    steps:
      - name: Flash with JLink
        run: JLink.exe -CommandFile C:\test\JLinkCommandFile.jlink

  testing:
    runs-on: [miniHIL_runner]
    needs: [prepare-miniHIL, prepare-motorController]
    steps:
      - name: T1A_12025_Longitudinal_Shift_range_of_motion
        run: .\gradlew.bat runTests "-Ptests=Seq_SetTableToTS7000;T1A_12025_Longitudinal_Shift_range_of_motion;"
        working-directory: c:\minihil\ts7x_motorcontroller_minihil\minihilpilot
